services:
  caddy:
    build:
      context: ../.
      dockerfile: Dockerfile
      args:
        - CADDY_VERSION=2.10.2
        - LINODE_PLUGIN_FORK=github.com/caddy-dns/linode@v0.8.0
    restart: unless-stopped
    network_mode: host
    volumes:
      - ${HOME_PORTAL_DIR}/Caddyfile:/etc/caddy/Caddyfile:ro
      - ${HOME_PORTAL_DIR}/config:/config
      - ${HOME_PORTAL_DIR}/data:/data
      - ${HOME_PORTAL_DIR}/site:/srv
    environment:
      - LINODE_DNS_PAT=${LINODE_DNS_PAT}
      - LINODE_API_URL=${LINODE_API_URL}
      - LINODE_API_VERSION=${LINODE_API_VERSION}
